import type { DictKey } from "./dict.en";

// Bangla strings. Typed so that a missing key is a compile error.
const bn: Record<DictKey, string> = {
  "app.name": "AgentEr Upay",
  "app.tagline": "upay এজেন্টদের জন্য তারল্য পূর্বাভাস",
  "banner.synthetic": "সিন্থেটিক ডেটা প্রোটোটাইপ। সংখ্যাগুলো কেবল প্রদর্শনের জন্য; অ্যাপ শুধু সুপারিশ দেয়, সিদ্ধান্ত নেন মানুষ।",
  "common.loading": "লোড হচ্ছে…", "common.error": "কিছু একটা ভুল হয়েছে", "common.retry": "আবার চেষ্টা করুন", "common.empty": "এখনো কিছু দেখানোর নেই",
  "common.save": "সংরক্ষণ", "common.cancel": "বাতিল", "common.close": "বন্ধ", "common.yes": "হ্যাঁ", "common.no": "না", "common.today": "আজ",
  "common.bdt": "টাকা", "common.day": "দিন", "common.days": "দিন", "common.of_capacity": "ধারণক্ষমতার", "common.none": "নেই",
  "common.all": "সব", "common.back": "ফিরে যান", "common.view": "দেখুন", "common.confirm": "নিশ্চিত করুন", "common.date": "তারিখ", "common.agent": "এজেন্ট",
  "common.division": "বিভাগ", "common.type": "ধরন", "common.status": "অবস্থা", "common.amount": "পরিমাণ", "common.note": "নোট",
  "common.optional": "ঐচ্ছিক", "common.network": "সার্ভারে সংযোগ করা যাচ্ছে না। API চালু আছে তো?",
  "nav.home": "হোম", "nav.report": "দৈনিক রিপোর্ট", "nav.forecast": "পূর্বাভাস", "nav.history": "ইতিহাস", "nav.overview": "ওভারভিউ",
  "nav.model": "মডেল ও প্রমাণ", "nav.dispatch": "ডিসপ্যাচ পরিকল্পনা", "nav.rules": "নিয়ম ও ইভেন্ট", "nav.impact": "প্রভাব ও মডেল", "nav.alerts": "সতর্কতা", "nav.logout": "লগ আউট",
  "nav.collapse": "মেনু ছোট করুন", "nav.expand": "মেনু বড় করুন", "nav.admin": "বিতরণ অফিস", "nav.menu": "মেনু",
  "theme.toggle": "থিম বদলান", "theme.light": "হালকা", "theme.dark": "গাঢ়", "theme.system": "সিস্টেম",
  "lang.toggle": "English", "lang.label": "ভাষা",
  "status.HIGH": "উচ্চ ঝুঁকি", "status.WATCH": "নজরে রাখুন", "status.OK": "ঠিক আছে",
  "term.cash": "নগদ", "term.efloat": "ই-ফ্লোট", "term.cashout": "ক্যাশ-আউট", "term.cashin": "ক্যাশ-ইন", "term.risk": "ফুরিয়ে যাওয়ার ঝুঁকি",
  "term.balance": "ব্যালেন্স", "term.capacity": "ধারণক্ষমতা", "term.median": "মধ্যমান", "term.mean": "গড়", "term.expected": "প্রত্যাশিত",

  "login.title": "স্বাগতম", "login.sub": "আপনার পূর্বাভাস দেখতে সাইন ইন করুন", "login.user": "এজেন্ট আইডি", "login.pass": "পাসওয়ার্ড",
  "login.submit": "সাইন ইন", "login.demo": "ডেমো অ্যাকাউন্ট", "login.demo.admin": "অ্যাডমিন: admin / admin123",
  "login.demo.agent": "এজেন্ট: আইডি “Agent A01”, পাসওয়ার্ড agenta01 (১৬ জনের জন্যই একই নিয়ম)", "login.err": "এজেন্ট আইডি বা পাসওয়ার্ড ভুল", "login.user.ph": "যেমন Agent A01", "login.agents": "এজেন্ট হিসেবে সাইন ইন করুন",
  "login.as_admin": "অ্যাডমিন (বিতরণ অফিস)", "login.as_agent": "এজেন্ট A01 (ডেমো)",

  "sim.clock": "সিমুলেশন ঘড়ি", "sim.advance": "১ দিন এগিয়ে নিন", "sim.jump": "তারিখে যান", "sim.go": "যান", "sim.play": "অটো-প্লে",
  "sim.pause": "থামান", "sim.end": "ডেটা শেষ", "sim.running": "রাতের পাইপলাইন চলছে…",
  "sim.pipeline": "{date} এর রাতের পাইপলাইন: {rows}টি লেজার সারি গৃহীত, {reports}টি নগদ রিপোর্ট চাওয়া হয়েছে, {fc}টি পূর্বাভাস পুনর্গণনা, {alerts}টি নতুন সতর্কতা ({ms} মি.সে.)",
  "sim.replay_note": "২০২৫ সালের সিন্থেটিক ডেটার রিপ্লে", "sim.range": "বৈধ তারিখ: {min} থেকে {max}", "sim.reset": "১ সেপ্টেম্বরে ফিরুন",
  "sim.bad_date": "বৈধ সীমার মধ্যে একটি তারিখ বাছুন",

  "home.hello": "হ্যালো, {name}", "home.today": "আজ · সিমুলেশন ঘড়ি", "home.balance_now": "এখনকার ব্যালেন্স",
  "home.next": "এরপর যা করবেন", "home.division": "{division} · {type}",
  "gauge.cash": "নগদ ফুরানোর ঝুঁকি", "gauge.efloat": "ই-ফ্লোট ফুরানোর ঝুঁকি",
  "gauge.sub": "পরবর্তী সম্ভাব্য টপ-আপের আগে ({n} দিনের সময়সীমা)", "gauge.of_cap": "ধারণক্ষমতার {pct}%",
  "gauge.runout": "{date} নাগাদ ফুরাতে পারে", "gauge.no_runout": "৭ দিনে ফুরানোর সম্ভাবনা নেই",
  "unit.type.garment_urban": "গার্মেন্ট এলাকা · শহর", "unit.type.rural": "গ্রামীণ", "unit.type.market_urban": "শহরের বাজার",
  "unit.type.university_urban": "বিশ্ববিদ্যালয় এলাকা · শহর", "unit.type.remittance_urban": "রেমিটেন্স · শহর",
  "unit.type.garment": "গার্মেন্ট", "unit.type.university": "বিশ্ববিদ্যালয়", "unit.type.market": "বাজার", "unit.type.remittance": "রেমিটেন্স",

  "action.cash_topup": "{date} এর আগে {amount} টাকা নগদ টপ-আপ করুন", "action.cash_topup.sub": "নগদ টপ-আপ মানে ই-ফ্লোটকে নগদে রূপান্তর করা।",
  "action.efloat_topup": "{date} এর আগে {amount} টাকা ই-ফ্লোট টপ-আপ করুন", "action.efloat_topup.sub": "ই-ফ্লোট টপ-আপ মানে নগদ দিয়ে ই-ফ্লোট কেনা।",
  "action.capital": "আগামী সময়ের জন্য আপনার মোট ফ্লোট খুব কম: প্রায় {amount} টাকা বাড়তি মূলধন দরকার।",
  "action.capital.sub": "নগদ আর ই-ফ্লোটের মধ্যে টাকা সরিয়ে এটা মেটানো যাবে না; আরও মূলধন দরকার।",
  "action.submit_report": "আজকের নগদ গণনা জমা দিন", "action.submit_report.sub": "আজকের নগদ লেজার থেকে অনুমান করা, এখনো নিশ্চিত হয়নি।",
  "action.verify_report": "অনুগ্রহ করে নগদ আবার গুনুন", "action.verify_report.sub": "আপনার গণনা লেজার থেকে {pct}% আলাদা। আপাতত লেজারের মান ব্যবহার হচ্ছে।",
  "action.all_good": "এখন কিছু করার দরকার নেই", "action.all_good.sub": "আগামী সময়ের জন্য ব্যালেন্স নিরাপদ মনে হচ্ছে।",
  "action.late": "সতর্কতা: পরবর্তী সম্ভাব্য টপ-আপ ফুরিয়ে যাওয়ার পরে পৌঁছাতে পারে।",
  "order.emergency": "জরুরি", "order.planned": "পরিকল্পিত",

  "rec.title": "নগদ মিলানো", "rec.ledger": "লেজার অনুযায়ী নগদ", "rec.reported": "আপনার গণনা", "rec.gap": "পার্থক্য",
  "rec.used": "পূর্বাভাসে ব্যবহৃত", "rec.status.confirmed": "নিশ্চিত", "rec.status.needs_verification": "যাচাই দরকার",
  "rec.status.missing": "অনুমান করা, আজ নিশ্চিত নয়", "rec.status.pending": "অনুমান করা, আজ নিশ্চিত নয়",
  "rec.source.reported": "আপনার গণনা", "rec.source.ledger_estimate": "লেজার অনুমান",
  "rec.warn.estimated": "আজকের নগদ লেজার থেকে অনুমান করা। গণনা করে নিশ্চিত করা হয়নি।",
  "rec.warn.verify": "গণনা লেজার অনুযায়ী নগদ থেকে {tol}% এর বেশি আলাদা। এটি যাচাই দরকার হিসেবে চিহ্নিত এবং পূর্বাভাসে লেজারের মান ব্যবহার হচ্ছে। আবার গুনলে সাহায্য হতে পারে।",
  "rec.none_yet": "এখনো কোনো গণনা জমা হয়নি",

  "report.title": "দৈনিক নগদ রিপোর্ট", "report.sub": "ড্রয়ারে থাকা প্রকৃত নগদ গুনে মোট পরিমাণ লিখুন।",
  "report.label": "গণনা করা নগদ (টাকা)", "report.placeholder": "যেমন 85000", "report.submit": "গণনা জমা দিন",
  "report.err.required": "নগদের পরিমাণ লিখুন", "report.err.number": "সঠিক সংখ্যা লিখুন", "report.err.negative": "পরিমাণ ০ বা তার বেশি হতে হবে",
  "report.err.big": "পরিমাণটি অনেক বড় মনে হচ্ছে। অনুগ্রহ করে দেখে নিন।", "report.result": "মিলানোর ফলাফল",
  "report.thanks": "ধন্যবাদ। আপনার গণনা সহনসীমার মধ্যে লেজারের সাথে মিলেছে এবং পূর্বাভাসে ব্যবহার করা হয়েছে।",
  "report.flagged": "আপনার গণনা লেজার অনুযায়ী নগদ থেকে আলাদা{gap}। এটি যাচাই দরকার হিসেবে চিহ্নিত এবং পূর্বাভাসে লেজারের মান ব্যবহার হয়েছে। আবার গুনলে সাহায্য হতে পারে।",
  "report.forecast_updated": "পূর্বাভাস হালনাগাদ হয়েছে", "report.new_risk": "এখন নগদ ফুরানোর ঝুঁকি", "report.for": "{date} এর রিপোর্ট",
  "report.submitted_toast": "নগদ গণনা পাওয়া গেছে",

  "fc.title": "৭ দিনের পূর্বাভাস", "fc.for": "{date} থেকে পূর্বাভাস",
  "fc.risk.headline": "পরবর্তী সম্ভাব্য টপ-আপের আগে ঝুঁকি", "fc.risk.7d": "কিছু না করলে ৭ দিনে",
  "dep.title": "খারাপ দিনগুলো কি একসাথে আসে? দিনে দিনে সম্পর্কসহ ও ছাড়া ঝুঁকি", "dep.line": "স্বাধীন দিন {a} → সম্পর্কসহ {b}",
  "dep.active": "উপরে দেখানো হয়েছে: {mode}", "dep.mode.t_copula": "স্টুডেন্ট-t কপুলা: খারাপ দিনগুলো একসাথে আসে (ডিফল্ট)", "dep.mode.correlated": "গাউসীয় সম্পর্কযুক্ত দিন", "dep.mode.ar1": "অটো-রিগ্রেসিভ পথ (AR(1))", "dep.mode.independent": "স্বাধীন দিন (সরবরাহকৃত ইঞ্জিনের ডিফল্ট)",
  "model.choice.challenger": "চ্যালেঞ্জার: আমাদের পুনঃপ্রশিক্ষিত, ক্যালিব্রেটেড মডেল (ডিফল্ট)", "model.choice.reference": "রেফারেন্স: সরবরাহকৃত মডেল", "rules.model": "পূর্বাভাস মডেল", "model.active": "মডেল: {model}",
  "model.title": "মডেল ও প্রমাণ", "model.sub": "পূর্বাভাস মডেল কীভাবে তৈরি, তুলনা, ক্যালিব্রেট ও পরীক্ষা করা হয়েছে। সিন্থেটিক ডেটায় অফলাইন ফলাফল।",
  "model.stamp": "সিন্থেটিক ডেটা। সময়ক্রম অনুযায়ী ভাগে নমুনার বাইরে পরীক্ষিত। প্রকৃত upay ডেটায় যাচাই করা হয়নি।",
  "model.active.now": "এখন ব্যবহৃত: {model} · পথ-নির্ভরতা: {dep}",
  "model.compare.title": "অস্পৃষ্ট পরীক্ষার সময়ে (১ সেপ্টেম্বর থেকে ৩১ ডিসেম্বর ২০২৫) মডেলগুলোর তুলনা", "model.compare.sub": "প্রতিটি মডেলের জন্য একই ভাগ, একই লেবেল, একই মাপকাঠি। ত্রুটি = মধ্যক পূর্বাভাসের WAPE; কভারেজ = পর্যবেক্ষিত ফলাফলের কত অংশ পরিসরের ভেতরে (লক্ষ্য ৮০%)।",
  "model.col.model": "মডেল", "model.col.wape_co": "WAPE আউট", "model.col.wape_ci": "WAPE ইন", "model.col.cov_co": "৮০% ঢাকে আউট", "model.col.cov_ci": "৮০% ঢাকে ইন", "model.col.pinball": "পিনবল", "model.col.width": "প্রস্থ",
  "model.fam.supplied_bundle": "সরবরাহকৃত বান্ডল (রেফারেন্স)", "model.fam.same_weekday_last_week": "গত সপ্তাহের একই বার (বেসলাইন)", "model.fam.lightgbm_ours": "LightGBM, আমাদের পুনঃপ্রশিক্ষণ",
  "model.fam.lightgbm_ours_cqr": "LightGBM + কনফর্মাল ক্যালিব্রেশন (চ্যালেঞ্জার)", "model.fam.lognormal_gbm": "লগ-নরমাল বুস্টেড মডেল", "model.fam.linear_quantile_regression": "রৈখিক কোয়ান্টাইল রিগ্রেশন", "model.fam.seasonal_profile": "মৌসুমি প্রোফাইল (এমএল ছাড়া)",
  "model.tag.insample": "ইন-স্যাম্পল: পুরো ২০২৫ এ প্রশিক্ষিত", "model.tag.deployed": "অ্যাপে ডিফল্ট",
  "model.cal.title": "পরিসরের ক্যালিব্রেশন", "model.cal.sub": "P10 থেকে P90 পরিসরের ভেতরে পর্যবেক্ষিত ফলাফলের অংশ। রেখাটি ৮০% লক্ষ্য।", "model.cal.before": "ক্যালিব্রেশনের আগে", "model.cal.after": "কনফর্মাল ক্যালিব্রেশনের পরে",
  "model.cal.note": "ক্যালিব্রেশনের প্রস্থ শুধু আগস্ট ২০২৫ থেকে নির্ধারিত, যে মাসে মডেল প্রশিক্ষণ নেয়নি, এবং প্রবাহ ও এজেন্টের ধরন অনুযায়ী প্রয়োগ করা হয়।",
  "model.unseen.title": "অদেখা এজেন্ট", "model.unseen.sub": "৪-ভাগ লিভ-এজেন্ট-আউট: প্রতিটি এজেন্টের পূর্বাভাস দেয় এমন মডেল যা তাকে কখনও দেখেনি।",
  "model.unseen.agent_seen": "একই মডেল, প্রশিক্ষণে দেখা এজেন্ট", "model.unseen.lightgbm_ours": "কখনও না দেখা এজেন্ট (কাঁচা)", "model.unseen.lightgbm_ours_cqr": "কখনও না দেখা এজেন্ট + ক্যালিব্রেশন", "model.unseen.lognormal_gbm": "কখনও না দেখা এজেন্ট, লগ-নরমাল মডেল", "model.unseen.seasonal_profile": "কখনও না দেখা এজেন্ট, মৌসুমি প্রোফাইল", "model.unseen.same_weekday_last_week": "বেসলাইন: গত সপ্তাহের একই বার",
  "model.event.title": "অদেখা ঘটনা: ঈদুল আযহা", "model.event.sub": "ঈদুল আযহার পুরো সময় (১৯ মে থেকে ২০ জুন) প্রশিক্ষণ থেকে বাদ দিয়ে তারপর পূর্বাভাস।",
  "model.event.adha_held_out": "ঈদ প্রশিক্ষণ থেকে বাদ", "model.event.adha_seen_in_training": "রেফারেন্স: ঈদ প্রশিক্ষণে দেখা", "model.event.seasonal_profile_adha_held_out": "মৌসুমি প্রোফাইল, ঈদ বাদ", "model.event.same_weekday_last_week": "বেসলাইন: গত সপ্তাহের একই বার",
  "model.event.note": "বিরল ঘটনা আংশিকভাবেই স্থানান্তরিত হয়, তাই হাতে ইভেন্ট ওভাররাইড আছে।",
  "model.path.title": "একাধিক দিনের পথ-নির্ভরতা ও প্রান্তিক ঝুঁকি", "model.path.sub": "সিমুলেটেড ৩ ও ৭ দিনের জমা চাহিদা বনাম যা ঘটেছে। প্রান্তিক ত্রুটি = ৫% / ১% প্রান্তিক ঘটনার পর্যবেক্ষিত ও লক্ষ্য হারের গড় ব্যবধান (কম ভালো)।",
  "model.path.col.3d": "প্রান্তিক ত্রুটি, ৩ দিন", "model.path.col.7d": "প্রান্তিক ত্রুটি, ৭ দিন", "model.path.col.cov": "পরিসরের ত্রুটি, ৭ দিন",
  "model.path.m.independent": "স্বাধীন দিন (সরবরাহকৃত ইঞ্জিন)", "model.path.m.correlated": "গাউসীয় কপুলা", "model.path.m.ar1": "অটো-রিগ্রেসিভ পথ (AR(1))", "model.path.m.t_copula_nu4": "স্টুডেন্ট-t কপুলা, nu = ৪", "model.path.m.t_copula_nu6": "স্টুডেন্ট-t কপুলা, nu = ৬ (ডিফল্ট)", "model.path.m.t_copula_nu10": "স্টুডেন্ট-t কপুলা, nu = ১০",
  "model.path.est": "জুলাই থেকে আগস্ট ২০২৫ এর {n}টি পূর্বাভাস উৎস থেকে নির্ণীত (মডেল প্রশিক্ষণে ব্যবহৃত নয়): দিনে দিনে সংযোগ {a}, ক্যাশ-আউট ও ক্যাশ-ইনের সংযোগ {b}।",
  "model.method.title": "এটি কীভাবে করা হয়েছে", "model.method.0": "লেবেল হলো পর্যবেক্ষিত প্রবাহ ও মজুত শেষের চিহ্ন। কোনো ফিচার বানানোর আগেই গ্রাউন্ড-ট্রুথ কলাম বাদ দেওয়া হয়।", "model.method.1": "লক্ষ্য তারিখ ধরে সময়ক্রমিক ভাগ: ৩০ জুন পর্যন্ত ফিট, জুলাইয়ে আর্লি স্টপিং, আগস্টে ক্যালিব্রেশন, ১ সেপ্টেম্বর থেকে পরীক্ষা।",
  "model.method.2": "সরবরাহকৃত মডেল রেফারেন্স হিসেবে রাখা হয়েছে। সেপ্টেম্বর থেকে ডিসেম্বরের তার সংখ্যাগুলো ইন-স্যাম্পল, শুধু প্রসঙ্গের জন্য।", "model.method.3": "সবকিছু backend/ml_train এ অফলাইনে চলে এবং একই ফরম্যাটের প্রকৃত, নিয়ন্ত্রিত ডেটায় আবার চালানো যায়।",
  "nav.economics": "আরওআই ও কভারেজ",
  "tier.garment_urban": "গার্মেন্ট (শহর)", "tier.market_urban": "বাজার (শহর)", "tier.remittance_urban": "রেমিটেন্স (শহর)", "tier.rural": "গ্রামীণ", "tier.university_urban": "বিশ্ববিদ্যালয় (শহর)",
  "eco.title": "আরওআই ও কভারেজ", "eco.sub": "পুনঃসরবরাহের যাত্রার খরচ বনাম অসেবিত গ্রাহকের ক্ষতি, এবং প্রতিটি এজেন্ট শ্রেণির জন্য সবচেয়ে সাশ্রয়ী নিরাপত্তা সেটিং।",
  "eco.banner": "যাত্রার খরচ, মার্জিন ও গ্রাহকের মূল্য এখন অনুমান মাত্র, upay প্রকৃত তথ্য দেওয়া পর্যন্ত। বদলালেই সবকিছু নতুন করে হিসাব হয়।",
  "eco.verdict.pays": "এই অনুমানে খরচ-সর্বোত্তম সেটিং এজেন্টের অভ্যাসের তুলনায় মোট খরচ {saved} ({pct}) কমায়, অর্ডার {habitOrders}টির বদলে {orders}টি এবং মজুত শেষের দিন {habitSo}টির বদলে {so}টি।",
  "eco.verdict.95.loses": "নির্দিষ্ট ৯৫% কভারেজ লক্ষ্য অভ্যাসের তুলনায় {amount} লোকসান করত, কারণ বাড়তি যাত্রার খরচ বাঁচানো বিক্রির চেয়ে বেশি।", "eco.verdict.95.gains": "নির্দিষ্ট ৯৫% কভারেজ লক্ষ্য অভ্যাসের তুলনায় {amount} বাঁচাত।",
  "eco.verdict.larger": "সঞ্চয়ের বেশিরভাগ আসে কম বার, বেশি পরিমাণে অর্ডার করা থেকে: বড় ভরায় যাত্রা কম লাগে, আর মডেল পুনঃঅর্ডারের স্তর এতটা উঁচু রাখে যাতে বেশিরভাগ মজুত শেষ এড়ানো যায়।",
  "eco.verdict.no": "এই অনুমানে এজেন্টের অভ্যাসই সবচেয়ে সাশ্রয়ী: বাড়তি যাত্রার খরচ আটকানো অসেবিত লেনদেনের চেয়ে বেশি। গ্রাহকের মূল্য বাড়ান বা যাত্রার খরচ কমান এবং নিচের সংবেদনশীলতা সারণি দেখুন।",
  "eco.policy.title": "নীতিগুলোর তুলনা, ১ সেপ্টেম্বর থেকে ২৪ ডিসেম্বর ২০২৫, ১৬ এজেন্ট", "eco.policy.sub": "লেজারের রিপ্লে। মজুত শেষের দিনে চাহিদা মডেল থেকে অনুমান করা, কোনো গোপন ডেটা নয়। এজেন্টের অভ্যাসের বেসলাইন লেজারে নথিভুক্ত মজুত শেষের সঙ্গে মেলানো।",
  "eco.col.policy": "নীতি", "eco.col.orders": "অর্ডার (যাত্রা)", "eco.col.so": "মজুত শেষের দিন", "eco.col.unserved": "অসেবিত (টাকা)", "eco.col.service": "সেবার হার", "eco.col.cost": "মোট খরচ (টাকা)", "eco.col.net": "অভ্যাসের তুলনায় নিট লাভ (টাকা)",
  "eco.pol.habit": "এজেন্টের অভ্যাস (৩০% এ অর্ডার, ৬৫% পর্যন্ত ভরা)", "eco.pol.hybrid95": "হাইব্রিড, নির্দিষ্ট ৯৫% কভারেজ", "eco.pol.optimum": "হাইব্রিড, শ্রেণি অনুযায়ী খরচ-সর্বোত্তম", "eco.pol.model_only95": "শুধু মডেল (ঠিক সময়ে)",
  "eco.assume.title": "অনুমান", "eco.assume.trip": "যাত্রার খরচ, {tier} (প্রতি অর্ডারে টাকা)", "eco.assume.margin": "লেনদেনে মার্জিন (%)", "eco.assume.agent_share": "ঐ মার্জিনে এজেন্টের অংশ (%)",
  "eco.assume.mult": "একজন অসেবিত গ্রাহকের মূল্য (একটি লেনদেনের গুণ)", "eco.assume.capital": "বাড়তি মূলধনের খরচ (বছরে %)", "eco.assume.save": "সংরক্ষণ করে পুনরায় হিসাব", "eco.assume.saved": "অনুমান সংরক্ষিত", "eco.assume.reset": "প্লেসহোল্ডার ফিরিয়ে আনুন",
  "eco.curve.title": "কভারেজের বিপরীতে মোট খরচ", "eco.curve.sub": "নির্বাচিত শ্রেণির জন্য রিপ্লে সময়ে যাত্রার খরচ, হারানো মার্জিন ও মূলধনের খরচের যোগফল। কম ভালো।", "eco.curve.tier": "এজেন্ট শ্রেণি",
  "eco.curve.default": "নিরাপত্তা বাফার ১০%, স্তর পর্যন্ত অর্ডার", "eco.curve.best": "প্রতিটি কভারেজে সেরা বাফার ও অর্ডারের আকার", "eco.curve.at95": "নির্দিষ্ট ৯৫% লক্ষ্য", "eco.curve.opt": "খরচ-সর্বোত্তম",
  "eco.tier.title": "শ্রেণি অনুযায়ী ফলাফল ও সেটিং", "eco.col.tier": "শ্রেণি (এজেন্ট)", "eco.col.agents": "এজেন্ট", "eco.col.net95": "৯৫% এ নিট", "eco.col.cov": "সেরা কভারেজ", "eco.col.buf": "বাফার", "eco.col.up": "এই পর্যন্ত অর্ডার",
  "eco.col.netopt": "সেরায় নিট", "eco.col.be_trip": "ব্রেক-ইভেন যাত্রা (৯৫%)", "eco.col.be_mult": "ব্রেক-ইভেন মূল্য (৯৫%)", "eco.col.applied": "এখন প্রযোজ্য", "eco.up.fmt": "স্তরের {n} গুণ",
  "eco.apply": "খরচ-সর্বোত্তম সেটিং প্রয়োগ করুন", "eco.apply.done": "খরচ-সর্বোত্তম সেটিং প্রয়োগ হয়েছে", "eco.apply.note": "শ্রেণি অনুযায়ী কভারেজ, নিরাপত্তা বাফার ও অর্ডারের আকার নিয়মে লেখে (অডিট-লগসহ)। এটি শুধু সুপারিশ বদলায়; সিদ্ধান্ত মানুষই নেয়।",
  "eco.applied.match": "সর্বোত্তমের সঙ্গে মেলে", "eco.applied.differs": "সর্বোত্তম থেকে আলাদা",
  "eco.sens.title": "সংবেদনশীলতা", "eco.sens.sub": "যাত্রার খরচ ও গ্রাহকের মূল্য বদলালে পুরো নেটওয়ার্কের জন্য সেরা একক সেটিং। প্রতিটি ঘর: কভারেজ, তারপর অভ্যাসের তুলনায় নিট লাভ।", "eco.sens.row": "যাত্রার খরচ x{scale}", "eco.sens.col": "গ্রাহক মূল্য x{m}", "eco.sens.pays": "লাভজনক", "eco.sens.no": "লাভজনক নয়",
  "rules.tier.note": "আরওআই ও কভারেজ পাতায় নির্ধারিত শ্রেণি অনুযায়ী কভারেজ, নিরাপত্তা বাফার ও অর্ডারের আকার এখানকার দুটি মানকে নিজ নিজ শ্রেণির জন্য ছাপিয়ে যায়। এখানে কভারেজ বা বাফার বদলালে সংশ্লিষ্ট শ্রেণি-মান মুছে যায়।", "rules.tier.link": "আরওআই ও কভারেজ খুলুন",
  "rules.dep": "দিনগুলোর মধ্যে চাহিদার সম্পর্ক",
  "fc.risk.why_two": "দুটি সংখ্যা কেন? কিছু না করলে ৭ দিনে প্রায় সবারই ঝুঁকি বেশি, কারণ ব্যালেন্স সবসময় কমে। গুরুত্বপূর্ণ সংখ্যা হলো সাহায্য পৌঁছানোর আগের ঝুঁকি। সাপ্তাহিক ছুটি ও সরকারি ছুটির আগে এই সময়সীমা বড় হয়।",
  "fc.risk.curve": "দিন অনুযায়ী ফুরিয়ে যাওয়ার সম্ভাবনা", "fc.runout.likely": "{date} নাগাদ ফুরাতে পারে", "fc.runout.none": "৭ দিনের মধ্যে ফুরানোর সম্ভাবনা নেই",
  "fc.window": "{n} দিনের সময়সীমা, {date} পর্যন্ত", "fc.day": "দিন {n}",
  "fc.cashout.title": "প্রতিদিনের ক্যাশ-আউট চাহিদা", "fc.cashin.title": "প্রতিদিনের ক্যাশ-ইন চাহিদা",
  "fc.band.80": "P10 থেকে P90 পরিসর", "fc.band.50": "P25 থেকে P75 পরিসর", "fc.median": "মধ্যমান", "fc.mean": "গড়",
  "fc.closed": "বন্ধের দিন (সাপ্তাহিক বা সরকারি ছুটি)", "fc.uncertain": "ছায়াযুক্ত পরিসর অনিশ্চয়তা দেখায়। কোনো একক সংখ্যা নিখুঁত নয়।",
  "fc.balance.cash": "নগদ ব্যালেন্সের প্রক্ষেপণ", "fc.balance.efloat": "ই-ফ্লোট ব্যালেন্সের প্রক্ষেপণ",
  "fc.balance.buffer": "বাফার রেখা (ধারণক্ষমতার {pct}%)", "fc.balance.p50": "মধ্যম পথ", "fc.balance.band": "P10 থেকে P90 পথ",
  "fc.balance.note": "কোনো টপ-আপ না এলে ব্যালেন্সের গতিপথ। ঝুঁকির সংখ্যাগুলোর একই সিমুলেশন থেকে এগুলো এসেছে।",
  "fc.table.title": "দিন অনুযায়ী", "fc.col.date": "তারিখ", "fc.col.median": "মধ্যমান", "fc.col.mean": "গড়", "fc.col.range": "P10 থেকে P90",
  "fc.col.surge": "ব্যস্ত দিনের সম্ভাবনা", "fc.col.open": "খোলা?", "fc.open": "খোলা", "fc.closed_short": "বন্ধ",
  "fc.surge.def": "ব্যস্ত দিন = চাহিদা আপনার ২৮ দিনের গড়ের {x} গুণের বেশি।", "fc.surge": "অস্বাভাবিক ব্যস্ত দিনের সম্ভাবনা",
  "fc.rec.title": "সুপারিশকৃত মজুত", "fc.rec.cash": "যে পরিমাণ নগদ রাখবেন", "fc.rec.efloat": "যে পরিমাণ ই-ফ্লোট রাখবেন", "fc.rec.current": "এখন",
  "fc.rec.recommended": "সুপারিশকৃত", "fc.rec.short": "{amount} টাকা কম", "fc.rec.above": "সুপারিশকৃত স্তরের চেয়ে {amount} টাকা বেশি",
  "fc.rec.topup": "প্রস্তাবিত টপ-আপ", "fc.rec.by": "{date} এর মধ্যে", "fc.rec.none": "টপ-আপ দরকার নেই",
  "fc.rec.cash_meaning": "নগদ টপ-আপ = ই-ফ্লোটকে নগদে রূপান্তর।", "fc.rec.efloat_meaning": "ই-ফ্লোট টপ-আপ = নগদ দিয়ে ই-ফ্লোট কেনা।",
  "fc.rec.coverage": "{n} দিনের সময়সীমা {p}% সম্ভাবনায় সুরক্ষিত রাখে, {b}% বাফারসহ।",
  "fc.rec.capital": "আগামী সময়ের জন্য আপনার মোট ফ্লোট খুব কম: প্রায় {amount} টাকা বাড়তি মূলধন দরকার।",
  "fc.rec.capital.detail": "দরকার {req} টাকা (নগদ {rc} + ই-ফ্লোট {re}), আছে {have} টাকা।",
  "fc.unserved": "সময়সীমার মধ্যে মডেল-অনুমানকৃত অপূর্ণ চাহিদা", "fc.unserved.note": "এটি মডেলের অনুমান, প্রকৃত সত্য নয়।",
  "fc.why.title": "এই পূর্বাভাস কেন", "fc.why.sub": "মধ্যমান পূর্বাভাসের শীর্ষ ৫ কারণ, মডেলের গড় স্তরের তুলনায় টাকায়।",
  "fc.why.day": "দিন", "fc.why.baseline": "গড় স্তর {n} টাকা", "fc.why.up": "বাড়ায়", "fc.why.down": "কমায়",
  "fc.why.flag.yes.up": "{label} প্রত্যাশিত চাহিদা বাড়ায়", "fc.why.flag.yes.down": "{label} প্রত্যাশিত চাহিদা কমায়",
  "fc.why.flag.no.up": "“{label}” নয়, তাই চাহিদা সব দিনের গড়ের চেয়ে বেশি",
  "fc.why.flag.no.down": "“{label}” নয়, তাই চাহিদা সব দিনের গড়ের চেয়ে কম",
  "fc.why.num.up": "{label} ({value}) প্রত্যাশিত চাহিদা বাড়ায়", "fc.why.num.down": "{label} ({value}) প্রত্যাশিত চাহিদা কমায়",
  "fc.why.note": "চিহ্ন সাবধানে পড়ুন: “সরকারি ছুটি: না, +3,184” মানে ওটা ছুটির দিন নয়, তাই চাহিদা সব দিনের গড়ের চেয়ে বেশি। ম্যানুয়াল সমন্বয় এই কারণগুলোর অংশ নয়।",
  "fc.manual": "ম্যানুয়াল সমন্বয়, মডেল এটি শেখেনি",
  "fc.manual.banner": "ম্যানুয়াল সমন্বয় চালু: {kind} ×{mult}, {start} থেকে {end}। এটি ম্যানুয়াল সমন্বয়, মডেল এটি শেখেনি।",
  "fc.source": "উৎস: মডেলের কোয়ান্টাইল + মন্টে কার্লো ঝুঁকি; সুপারিশকৃত স্তর ও টপ-আপ নথিভুক্ত নিয়ম অনুসরণ করে।",
  "fc.status.sentence": "সার্বিক অবস্থা", "fc.cash_out_heading": "নগদ", "fc.ef_heading": "ই-ফ্লোট",
  "fc.open_forecast": "পূর্বাভাস খুলুন", "fc.loading_why": "কারণ লোড হচ্ছে…", "fc.tab.cash": "ক্যাশ-আউট", "fc.tab.efloat": "ক্যাশ-ইন",

  "hist.title": "ইতিহাস", "hist.range": "গত {n} দিন", "hist.balances": "দিনশেষের ব্যালেন্স", "hist.cash": "নগদ", "hist.efloat": "ই-ফ্লোট",
  "hist.topup": "টপ-আপ এসেছে", "hist.stockout": "মজুত শেষ", "hist.stockout_days": "মজুত শেষ হওয়া দিন", "hist.topups": "প্রাপ্ত টপ-আপ",
  "hist.table": "দৈনিক লগ", "hist.col.cash": "নগদ", "hist.col.efloat": "ই-ফ্লোট", "hist.col.topup": "টপ-আপ", "hist.col.flags": "চিহ্ন",
  "hist.col.report": "নগদ রিপোর্ট", "hist.cash_topup": "নগদ টপ-আপ", "hist.efloat_topup": "ই-ফ্লোট টপ-আপ", "hist.so.cash": "নগদ ফুরিয়েছে", "hist.so.efloat": "ই-ফ্লোট ফুরিয়েছে",
  "hist.none": "কোনো চিহ্ন নেই",

  "alerts.title": "সতর্কতা", "alerts.open": "খোলা", "alerts.acked": "স্বীকৃত", "alerts.ack": "স্বীকার করুন", "alerts.none": "কোনো সতর্কতা নেই",
  "alerts.type.risk_high": "ফুরানোর উচ্চ ঝুঁকি", "alerts.type.risk_watch": "নজরে রাখুন: ঝুঁকি বাড়ছে", "alerts.type.report_missing": "নগদ রিপোর্ট নেই",
  "alerts.type.report_requested": "নগদ রিপোর্ট চাওয়া হয়েছে", "alerts.type.report_gap": "রিপোর্ট যাচাই দরকার", "alerts.type.capital": "বাড়তি মূলধনের প্রস্তাব",
  "alerts.msg.risk_high": "{agent}: পরবর্তী সম্ভাব্য টপ-আপের আগে ফুরানোর উচ্চ ঝুঁকি (নগদ {c}%, ই-ফ্লোট {e}%, {w} দিনের সময়সীমা)।",
  "alerts.msg.risk_watch": "{agent}: নজরে রাখুন, ফুরানোর ঝুঁকি বাড়ছে (নগদ {c}%, ই-ফ্লোট {e}%, {w} দিনের সময়সীমা)।",
  "alerts.msg.report_missing": "{agent}: {date} এর নগদ রিপোর্ট নেই। লেজার থেকে অনুমান করা, আজ নিশ্চিত নয়।",
  "alerts.msg.report_requested": "{agent}: {date} এর দৈনিক নগদ রিপোর্ট চাওয়া হয়েছে।",
  "alerts.msg.report_gap": "{agent}: জানানো নগদ লেজার অনুযায়ী নগদ থেকে আলাদা{gap}। যাচাইয়ের জন্য চিহ্নিত; লেজারের মান ব্যবহার হয়েছে।",
  "alerts.msg.capital": "{agent}: আগামী সময়ের জন্য মোট ফ্লোট কম হতে পারে; প্রায় {amount} টাকা বাড়তি মূলধনের প্রস্তাব।",
  "alerts.sev.high": "উচ্চ", "alerts.sev.watch": "নজর", "alerts.sev.info": "তথ্য",

  "adm.overview.title": "নেটওয়ার্ক ওভারভিউ", "adm.overview.sub": "ফুরানোর ঝুঁকি অনুযায়ী সাজানো সব ১৬ জন এজেন্ট",
  "kpi.high": "উচ্চ ঝুঁকির এজেন্ট", "kpi.watch": "নজরে থাকা এজেন্ট", "kpi.unserved": "প্রত্যাশিত অপূর্ণ চাহিদা", "kpi.unserved.note": "মডেলের অনুমান, সময়সীমার মধ্যে",
  "kpi.topup": "পরিকল্পিত টপ-আপ মোট", "kpi.topup.note": "নগদ {c} + ই-ফ্লোট {e}", "kpi.capital": "মূলধন দরকার এমন এজেন্ট", "kpi.capital.note": "মোট ফ্লোট খুব কম",
  "kpi.reports": "অনুসরণযোগ্য রিপোর্ট", "kpi.reports.note": "{m}টি নেই বা অপেক্ষমাণ · {f}টি চিহ্নিত",
  "tbl.rank": "#", "tbl.agent": "এজেন্ট", "tbl.cash_risk": "নগদ ঝুঁকি", "tbl.ef_risk": "ই-ফ্লোট ঝুঁকি", "tbl.runout": "সম্ভাব্য ফুরানো", "tbl.topup": "সুপারিশকৃত টপ-আপ",
  "tbl.report": "রিপোর্ট", "tbl.status": "অবস্থা", "tbl.capital": "মূলধন", "tbl.window": "সময়সীমা",
  "tbl.filter.division": "বিভাগ", "tbl.filter.type": "অবস্থানের ধরন", "tbl.filter.status": "অবস্থা", "tbl.filter.reset": "ফিল্টার মুছুন",
  "tbl.none": "এই ফিল্টারে কোনো এজেন্ট মেলেনি", "tbl.cash_short": "নগদ", "tbl.ef_short": "ই-ফ্লোট", "tbl.needs_capital": "মূলধন দরকার",
  "tbl.no_runout": "৭ দিনে নেই", "tbl.event": "ম্যানুয়াল সমন্বয় চালু",
  "div.title": "বিভাগসমূহ", "div.agents": "{n} জন এজেন্ট", "div.worst": "সবচেয়ে খারাপ অবস্থা", "div.topup": "টপ-আপ {amount} টাকা",
  "adm.agent.title": "এজেন্টের বিস্তারিত", "adm.agent.back": "ওভারভিউতে ফিরুন", "adm.agent.recon": "মিলানোর ইতিহাস", "adm.agent.alerts": "সতর্কতার লগ",
  "adm.agent.reveal": "ডেমো প্রকাশ: আসলে কী ঘটেছিল", "adm.agent.reveal.sub": "পরের ৭ দিনের চার্টে সিন্থেটিক প্রকৃত তথ্য যোগ করে।",
  "adm.agent.reveal.unavailable": "তারিখের পরে ৭ দিনের পূর্ণ ডেটা দরকার (শেষ শুরুর তারিখ {date})।",
  "reveal.banner": "ডেমো প্রকাশ: সিন্থেটিক প্রকৃত তথ্য, এজেন্টদের কাছে বা বাস্তবে পাওয়া যায় না।",
  "reveal.true": "প্রকৃত চাহিদা", "reveal.served": "সেবা দেওয়া (লেজার)", "reveal.outcome": "আসলে কী ঘটেছিল", "reveal.unserved": "অপূর্ণ {amount} টাকা",
  "reveal.stockouts": "মজুত শেষের দিন: নগদ {c}, ই-ফ্লোট {e}", "reveal.counterfactual": "টপ-আপ না এলে ব্যালেন্স",
  "reveal.breach.yes": "টপ-আপ ছাড়া ব্যালেন্স বাফারের নিচে নেমে যেত", "reveal.breach.no": "টপ-আপ ছাড়াও ব্যালেন্স বাফারের উপরে থাকত",
  "reveal.col.true": "প্রকৃত", "reveal.col.served": "সেবা দেওয়া",

  "disp.title": "ডিসপ্যাচ পরিকল্পনা", "disp.sub": "পরবর্তী কার্যদিবসের জন্য সুপারিশকৃত টপ-আপ: {date}", "disp.cash_total": "বরাদ্দের নগদ",
  "disp.ef_total": "বরাদ্দের ই-ফ্লোট", "disp.orders": "তৈরি অর্ডার", "disp.emergency": "জরুরি", "disp.planned_n": "পরিকল্পিত",
  "disp.by": "যে তারিখের মধ্যে", "disp.ack": "স্বীকার করুন", "disp.schedule": "সময় ঠিক করুন", "disp.done": "সম্পন্ন চিহ্নিত করুন", "disp.cancel": "অর্ডার বাতিল",
  "disp.status.proposed": "প্রস্তাবিত", "disp.status.acknowledged": "স্বীকৃত", "disp.status.scheduled": "নির্ধারিত", "disp.status.done": "সম্পন্ন", "disp.status.cancelled": "বাতিল",
  "disp.no_items": "এই তারিখে কোনো টপ-আপের সুপারিশ নেই", "disp.needs_capital": "মূলধন দরকার: {agents}", "disp.urgent": "পরবর্তী কার্যদিবস",
  "disp.later": "অপেক্ষা করা যায়", "disp.sched_for": "নির্ধারিত তারিখ", "disp.pick_date": "তারিখ বাছুন", "disp.created": "অর্ডার তৈরি হয়েছে", "disp.updated": "অর্ডার হালনাগাদ হয়েছে",
  "disp.note": "শুধু সুপারিশ। প্রতিটি অর্ডার মানুষ ঠিক করেন ও ব্যবস্থা নেন।", "disp.risk": "ঝুঁকি", "disp.runout": "সম্ভাব্য ফুরানো",
  "disp.capital_gap": "প্রায় {amount} টাকা বাড়তি মূলধন", "disp.orders_log": "অর্ডারসমূহ",

  "rules.title": "নিয়ম ও ইভেন্ট", "rules.sub": "ব্যবসায়িক নিয়ম মডেলের বাইরে থাকে। বদলালে মডেলের ঝুঁকি-সেটিংসের একটি কপিতে পূর্বাভাস আবার চলে। কিছুই নতুন করে প্রশিক্ষণ হয় না।",
  "rules.buffer": "বাফার (যে অংশ ধারণক্ষমতা ‘কার্যত শেষ’ ধরা হয়)", "rules.coverage": "সুপারিশকৃত স্তরের জন্য কভারেজ সম্ভাবনা",
  "rules.min_order": "ন্যূনতম টপ-আপ (ধারণক্ষমতার অংশ)", "rules.high": "উচ্চ ঝুঁকির সীমা (ঝুঁকি %)", "rules.watch": "নজরের সীমা (ঝুঁকি %)",
  "rules.tol": "মিলানোর সহনসীমা (লেজার নগদের অংশ)", "rules.manual": "যাদের রিপোর্ট অপেক্ষমাণ থাকে (ডেমো)", "rules.manual.help": "কমা দিয়ে এজেন্ট আইডি, যেমন A01",
  "rules.save": "নিয়ম সংরক্ষণ ও পূর্বাভাস পুনরায় চালান", "rules.saved": "নিয়ম সংরক্ষিত। পূর্বাভাস আবার চলেছে।", "rules.reset": "ডিফল্ট ফিরিয়ে আনুন", "rules.hash": "কনফিগ ফিঙ্গারপ্রিন্ট",
  "rules.bounds": "অনুমোদিত: {lo} থেকে {hi}", "rules.invalid": "চিহ্নিত মানগুলো দেখুন",
  "events.title": "স্থানীয় ইভেন্ট ওভাররাইড", "events.sub": "এলাকার ইভেন্ট চাহিদার গুণক হিসেবে দিন। ঝুঁকি সিমুলেশনের আগে এটি পূর্বাভাসের কোয়ান্টাইলে প্রয়োগ হয়।",
  "events.badge": "ম্যানুয়াল সমন্বয়, মডেল এটি শেখেনি", "events.scope": "প্রযোজ্য", "events.scope.all": "সব এজেন্ট", "events.scope.division": "একটি বিভাগ",
  "events.scope.agent": "একজন এজেন্ট", "events.target": "লক্ষ্য", "events.kind": "ইভেন্ট", "events.kind.fair": "মেলা", "events.kind.road_closure": "সড়ক বন্ধ",
  "events.kind.flood": "বন্যা", "events.kind.other": "অন্যান্য", "events.flow": "প্রভাবিত", "events.flow.both": "ক্যাশ-আউট ও ক্যাশ-ইন", "events.flow.cashout": "শুধু ক্যাশ-আউট",
  "events.flow.cashin": "শুধু ক্যাশ-ইন", "events.mult": "চাহিদার গুণক", "events.mult.help": "১.০ = অপরিবর্তিত; ১.৫ = ৫০% বেশি; ০.৫ = অর্ধেক", "events.start": "শুরু", "events.end": "শেষ",
  "events.add": "ইভেন্ট যোগ করুন", "events.added": "ইভেন্ট যোগ হয়েছে। পূর্বাভাস হালনাগাদ।", "events.none": "এখনো কোনো ইভেন্ট নেই", "events.remove": "নিষ্ক্রিয় করুন", "events.removed": "ইভেন্ট নিষ্ক্রিয় হয়েছে",
  "events.active": "সক্রিয়", "events.inactive": "নিষ্ক্রিয়", "events.note": "নোট",
  "audit.title": "অডিট লগ", "audit.none": "কোনো এন্ট্রি নেই", "audit.when": "কখন", "audit.who": "কে", "audit.what": "কাজ",

  "impact.title": "প্রভাব ও মডেল কার্ড", "impact.sub": "অফলাইন মূল্যায়ন, প্রকৃত upay ডেটায় মাপা নয়", "impact.label": "সিন্থেটিক ডেটায় সিমুলেশন",
  "impact.policy.title": "নীতি রিপ্লে: ১ সেপ্টেম্বর থেকে ২৪ ডিসেম্বর ২০২৫, ১৬ এজেন্ট (১১৫ দিন)", "impact.policy.stockouts": "মজুত শেষ হওয়া দিন", "impact.policy.unserved": "অপূর্ণ চাহিদা (টাকা)",
  "impact.policy.orders": "অর্ডার সংখ্যা (খরচের দিক)", "impact.policy.cash": "নগদ {n}", "impact.policy.ef": "ই-ফ্লোট {n}",
  "impact.policy.habit": "এজেন্টের অভ্যাস", "impact.policy.hybrid": "হাইব্রিড (সুপারিশকৃত)", "impact.policy.model_only": "শুধু মডেল (ঠিক সময়ে)",
  "impact.policy.habit.rule": "ধারণক্ষমতার ৩০% এর নিচে অর্ডার, ৬৫% পর্যন্ত টপ-আপ", "impact.policy.hybrid.rule": "৯৫% কভারেজে মডেলের প্রয়োজনে অভ্যাসের বাফার বাড়ানো",
  "impact.policy.model_only.rule": "মডেলের সুপারিশকৃত স্তরের নিচে নামলেই কেবল অর্ডার",
  "impact.headline": "অভ্যাসের তুলনায় হাইব্রিড: মজুত শেষের দিন {s}%, অপূর্ণ চাহিদা {u}%, কিন্তু অর্ডার {o}% বেশি।",
  "impact.cost": "এটা বিনা খরচে নয়: হাইব্রিডে অর্ডার (যাত্রা) বেশি হয়। এটা সার্থক কি না নির্ভর করে একটি যাত্রার খরচ বনাম একজন অসেবিত গ্রাহকের ক্ষতির উপর।",
  "impact.model_only": "শুধু মডেল (ঠিক সময়ে) মজুত শেষের দিনে এজেন্টের অভ্যাসের চেয়ে খারাপ ({d} বনাম {h})। মডেলের মূল্য হলো অভ্যাসের বাফার কখন যথেষ্ট নয় তা জানা, অভ্যাসকে প্রতিস্থাপন করা নয়।",
  "impact.frontier.title": "কভারেজের ট্রেড-অফ", "impact.frontier.x": "অর্ডার সংখ্যা (খরচ)", "impact.frontier.y": "মজুত শেষের দিন (ক্ষতি)",
  "impact.frontier.habit": "এজেন্টের অভ্যাস", "impact.frontier.note": "কভারেজ একটি ব্যবসায়িক সিদ্ধান্ত: বেশি নিরাপত্তা মানে কম মজুত শেষ কিন্তু বেশি অর্ডার।",
  "impact.type.title": "এজেন্টের ধরন অনুযায়ী মজুত শেষ কমা", "impact.type.garment_note": "গার্মেন্টের মূলধন দরকার: {p}% দিনে তার ৯৫% প্রয়োজন মোট ফ্লোটকে ছাড়িয়ে যায় (গড় ঘাটতি {s} টাকা)।",
  "impact.type.rural": "গ্রামীণ", "impact.type.university": "বিশ্ববিদ্যালয়", "impact.type.market": "বাজার", "impact.type.garment": "গার্মেন্ট", "impact.type.remittance_urban": "রেমিটেন্স শহর",
  "impact.acc.title": "পূর্বাভাসের নির্ভুলতা (WAPE, সেপ্টেম্বর–ডিসেম্বর পরীক্ষা)", "impact.acc.model": "মডেল", "impact.acc.baseline": "গত সপ্তাহের একই বার", "impact.acc.floor": "সিন্থেটিক নয়েজ সীমা",
  "impact.acc.cashout": "ক্যাশ-আউট", "impact.acc.cashin": "ক্যাশ-ইন", "impact.acc.cover": "৮০% পরিসর বাস্তবে ঢাকে {a}% (ক্যাশ-আউট) ও {b}% (ক্যাশ-ইন)",
  "impact.acc.unseen_agent": "অদেখা এজেন্ট: {u}, দেখা থাকলে {s} (ক্যাশ-আউট)", "impact.acc.unseen_festival": "অদেখা উৎসব (ঈদুল আযহা বাদ রেখে): ক্যাশ-আউট {a}, ক্যাশ-ইন {b}",
  "impact.lim.title": "সীমাবদ্ধতা", "impact.lim.0": "সিন্থেটিক ডেটা: মডেল ইচ্ছাকৃতভাবে বসানো প্যাটার্নই শেখে, তাই ফলাফল পাইপলাইন যাচাই করে, বাস্তব নির্ভুলতা নয়।",
  "impact.lim.1": "শুধু এক বছরের (২০২৫) ডেটা।", "impact.lim.2": "মডেল পুরো ২০২৫ এ প্রশিক্ষিত, তাই রিপ্লের তারিখগুলো মোতায়েন করা মডেলের জন্য ইন-স্যাম্পল।",
  "impact.lim.3": "ঝুঁকি ইঞ্জিন দিনগুলোকে স্বাধীন ধরে, তাই প্রান্তিক ঝুঁকি সম্ভবত কম দেখায়।", "impact.lim.4": "শুধু সুপারিশ: সিদ্ধান্ত নেন মানুষ, কিছুই স্বয়ংক্রিয় নয়।",
  "impact.lim.5": "কোনো পাইলটের আগে যাচাইয়ের জন্য নিয়ন্ত্রিত upay ডেটা দরকার।",
  "impact.card.title": "মডেল কার্ড", "impact.card.model": "মডেল", "impact.card.trained": "প্রশিক্ষণের ডেটা", "impact.card.libs": "লাইব্রেরি", "impact.card.horizon": "সময়সীমা",
  "impact.card.horizon_v": "৭ দিন, কোয়ান্টাইল P10, P25, P50, P75, P90", "impact.card.rules": "ব্যবসায়িক নিয়ম (বাফার, কভারেজ, টপ-আপের পরিমাণ, ওভাররাইড) মডেলের বাইরে থাকে।",
  "impact.card.llm": "সংখ্যা বা সিদ্ধান্তের জন্য কোনো LLM ব্যবহার হয় না। ব্যাখ্যাগুলো নির্ধারিত টেমপ্লেট থেকে তৈরি।",
  "feat.base": "গড় স্তর",
};

export default bn;
