// English strings. Bangla (dict.bn.ts) must define exactly the same keys (enforced by the type).
const en = {
  "app.name": "AgentEr Upay",
  "app.tagline": "Liquidity forecasting for upay agents",
  "banner.synthetic": "Synthetic data prototype. Numbers are for demonstration; the app gives recommendations only, people decide.",
  "common.loading": "Loading…", "common.error": "Something went wrong", "common.retry": "Try again", "common.empty": "Nothing to show yet",
  "common.save": "Save", "common.cancel": "Cancel", "common.close": "Close", "common.yes": "yes", "common.no": "no", "common.today": "Today",
  "common.bdt": "BDT", "common.day": "day", "common.days": "days", "common.of_capacity": "of capacity", "common.none": "None",
  "common.all": "All", "common.back": "Back", "common.view": "View", "common.confirm": "Confirm", "common.date": "Date", "common.agent": "Agent",
  "common.division": "Division", "common.type": "Type", "common.status": "Status", "common.amount": "Amount", "common.note": "Note",
  "common.optional": "optional", "common.network": "Cannot reach the server. Is the API running?",
  "nav.home": "Home", "nav.report": "Daily report", "nav.forecast": "Forecast", "nav.history": "History", "nav.overview": "Overview",
  "nav.dispatch": "Dispatch plan", "nav.rules": "Rules & events", "nav.impact": "Impact & model", "nav.alerts": "Alerts", "nav.logout": "Log out",
  "nav.collapse": "Collapse menu", "nav.expand": "Expand menu", "nav.admin": "Distribution office", "nav.menu": "Menu",
  "theme.toggle": "Switch theme", "theme.light": "Light", "theme.dark": "Dark", "theme.system": "System",
  "lang.toggle": "বাংলা", "lang.label": "Language",
  "status.HIGH": "High risk", "status.WATCH": "Watch", "status.OK": "OK",
  "term.cash": "Cash", "term.efloat": "E-float", "term.cashout": "Cash-out", "term.cashin": "Cash-in", "term.risk": "Run-out risk",
  "term.balance": "Balance", "term.capacity": "Capacity", "term.median": "Median", "term.mean": "Mean", "term.expected": "Expected",

  "login.title": "Welcome back", "login.sub": "Sign in to see your forecast", "login.user": "Agent ID", "login.pass": "Password",
  "login.submit": "Sign in", "login.demo": "Demo accounts", "login.demo.admin": "Admin: admin / admin123",
  "login.demo.agent": "Agent: ID “Agent A01”, password agenta01 (same pattern for all 16)", "login.err": "Wrong Agent ID or password", "login.user.ph": "e.g. Agent A01", "login.agents": "Sign in as an agent",
  "login.as_admin": "Admin (distribution office)", "login.as_agent": "Agent A01 (demo)",

  "sim.clock": "Simulation clock", "sim.advance": "Advance 1 day", "sim.jump": "Jump to date", "sim.go": "Go", "sim.play": "Auto-play",
  "sim.pause": "Pause", "sim.end": "End of data", "sim.running": "Running nightly pipeline…",
  "sim.pipeline": "Nightly pipeline for {date}: {rows} ledger rows ingested, {reports} cash reports requested, {fc} forecasts recomputed, {alerts} new alerts ({ms} ms)",
  "sim.replay_note": "Replay of 2025 synthetic data", "sim.range": "Valid dates: {min} to {max}", "sim.reset": "Reset to 1 Sep",
  "sim.bad_date": "Pick a date inside the valid range",

  "home.hello": "Hello, {name}", "home.today": "Today · simulation clock", "home.balance_now": "Balance now",
  "home.next": "Do this next", "home.division": "{division} · {type}",
  "gauge.cash": "Cash run-out risk", "gauge.efloat": "E-float run-out risk",
  "gauge.sub": "before the next possible top-up ({n}-day window)", "gauge.of_cap": "{pct}% of capacity",
  "gauge.runout": "Likely to run out {date}", "gauge.no_runout": "No run-out expected in 7 days",
  "unit.type.garment_urban": "Garment area · urban", "unit.type.rural": "Rural", "unit.type.market_urban": "Urban market",
  "unit.type.university_urban": "University area · urban", "unit.type.remittance_urban": "Remittance · urban",
  "unit.type.garment": "Garment", "unit.type.university": "University", "unit.type.market": "Market", "unit.type.remittance": "Remittance",

  "action.cash_topup": "Top up BDT {amount} cash before {date}", "action.cash_topup.sub": "A cash top-up means converting e-float into cash.",
  "action.efloat_topup": "Top up BDT {amount} e-float before {date}", "action.efloat_topup.sub": "An e-float top-up means buying e-float with cash.",
  "action.capital": "Your total float is too small for the coming window: needs extra capital of about BDT {amount}.",
  "action.capital.sub": "Moving money between cash and e-float cannot fix this; more capital is needed.",
  "action.submit_report": "Submit today's cash count", "action.submit_report.sub": "Today's cash is estimated from the ledger and not confirmed yet.",
  "action.verify_report": "Please recount your cash", "action.verify_report.sub": "Your count differs from the ledger by {pct}%. The ledger value is used for now.",
  "action.all_good": "No action needed right now", "action.all_good.sub": "Balances look safe for the coming window.",
  "action.late": "Heads-up: the next possible top-up may arrive after the likely run-out.",
  "order.emergency": "Emergency", "order.planned": "Planned",

  "rec.title": "Cash reconciliation", "rec.ledger": "Ledger-implied cash", "rec.reported": "Your count", "rec.gap": "Difference",
  "rec.used": "Used for the forecast", "rec.status.confirmed": "Confirmed", "rec.status.needs_verification": "Needs verification",
  "rec.status.missing": "Estimated, not confirmed today", "rec.status.pending": "Estimated, not confirmed today",
  "rec.source.reported": "Your count", "rec.source.ledger_estimate": "Ledger estimate",
  "rec.warn.estimated": "Today's cash is an estimate from the ledger. It has not been confirmed by a count.",
  "rec.warn.verify": "The count differs from the ledger-implied cash by more than {tol}%. It is marked as needing verification and the forecast uses the ledger value. A recount may help.",
  "rec.none_yet": "No count submitted yet",

  "report.title": "Daily cash report", "report.sub": "Count the physical cash in your drawer and enter the total.",
  "report.label": "Cash counted (BDT)", "report.placeholder": "e.g. 85000", "report.submit": "Submit count",
  "report.err.required": "Enter the cash amount", "report.err.number": "Enter a valid number", "report.err.negative": "Amount must be 0 or more",
  "report.err.big": "That amount looks too large. Please check it.", "report.result": "Reconciliation result",
  "report.thanks": "Thank you. Your count matches the ledger within tolerance and was used for the forecast.",
  "report.flagged": "Your count differs from the ledger-implied cash{gap}. It is marked as needing verification and the ledger value is used for the forecast. A recount may help.",
  "report.forecast_updated": "Forecast updated", "report.new_risk": "Cash run-out risk now", "report.for": "Report for {date}",
  "report.submitted_toast": "Cash count received",

  "fc.title": "7-day forecast", "fc.for": "Forecast from {date}",
  "fc.risk.headline": "Risk before the next possible top-up", "fc.risk.7d": "7 days if nothing is done",
  "fc.risk.why_two": "Why two numbers? Over 7 days of doing nothing, risk is high for almost everyone because balances always drain. The number that matters is the risk before help can arrive. That window gets longer before weekends and holidays.",
  "fc.risk.curve": "Chance of running out by day", "fc.runout.likely": "Likely to run out on {date}", "fc.runout.none": "No run-out expected within 7 days",
  "fc.window": "{n}-day window, until {date}", "fc.day": "Day {n}",
  "fc.cashout.title": "Cash-out demand per day", "fc.cashin.title": "Cash-in demand per day",
  "fc.band.80": "P10 to P90 range", "fc.band.50": "P25 to P75 range", "fc.median": "Median", "fc.mean": "Mean",
  "fc.closed": "Closed day (weekend or holiday)", "fc.uncertain": "Shaded bands show uncertainty. No single number is exact.",
  "fc.balance.cash": "Cash balance projection", "fc.balance.efloat": "E-float balance projection",
  "fc.balance.buffer": "Buffer line ({pct}% of capacity)", "fc.balance.p50": "Median path", "fc.balance.band": "P10 to P90 path",
  "fc.balance.note": "Balances if no top-up arrives. Paths come from the same simulations as the risk numbers.",
  "fc.table.title": "Day by day", "fc.col.date": "Date", "fc.col.median": "Median", "fc.col.mean": "Mean", "fc.col.range": "P10 to P90",
  "fc.col.surge": "Busy-day chance", "fc.col.open": "Open?", "fc.open": "Open", "fc.closed_short": "Closed",
  "fc.surge.def": "Busy day = demand above {x}× your 28-day average.", "fc.surge": "Chance of an unusually busy day",
  "fc.rec.title": "Recommended inventory", "fc.rec.cash": "Cash to hold", "fc.rec.efloat": "E-float to hold", "fc.rec.current": "Now",
  "fc.rec.recommended": "Recommended", "fc.rec.short": "Short by BDT {amount}", "fc.rec.above": "BDT {amount} above the recommended level",
  "fc.rec.topup": "Suggested top-up", "fc.rec.by": "by {date}", "fc.rec.none": "No top-up needed",
  "fc.rec.cash_meaning": "Cash top-up = convert e-float into cash.", "fc.rec.efloat_meaning": "E-float top-up = buy e-float with cash.",
  "fc.rec.coverage": "Protects the {n}-day window with {p}% probability, keeping a {b}% buffer.",
  "fc.rec.capital": "Your total float is too small for the coming window: needs extra capital of about BDT {amount}.",
  "fc.rec.capital.detail": "Needs BDT {req} (cash {rc} + e-float {re}), holds BDT {have}.",
  "fc.unserved": "Model-estimated unserved demand in the window", "fc.unserved.note": "A model estimate, not ground truth.",
  "fc.why.title": "Why this forecast", "fc.why.sub": "Top 5 drivers for the median forecast, in BDT versus the model's average level.",
  "fc.why.day": "Day", "fc.why.baseline": "Average level BDT {n}", "fc.why.up": "adds", "fc.why.down": "reduces",
  "fc.why.flag.yes.up": "{label} raises expected demand", "fc.why.flag.yes.down": "{label} lowers expected demand",
  "fc.why.flag.no.up": "Not “{label}”, so demand is higher than the all-days average",
  "fc.why.flag.no.down": "Not “{label}”, so demand is lower than the all-days average",
  "fc.why.num.up": "{label} ({value}) raises expected demand", "fc.why.num.down": "{label} ({value}) lowers expected demand",
  "fc.why.note": "Read signs carefully: “public holiday: no, +3,184” means it is not a holiday, so demand is higher than the all-days average. Manual adjustments are not part of these drivers.",
  "fc.manual": "manual adjustment, not learned by the model",
  "fc.manual.banner": "Manual adjustment active: {kind} ×{mult} from {start} to {end}. This is a manual adjustment, not learned by the model.",
  "fc.source": "Source: model quantiles + Monte Carlo risk; recommended level and top-up follow documented rules.",
  "fc.status.sentence": "Overall status", "fc.cash_out_heading": "Cash", "fc.ef_heading": "E-float",
  "fc.open_forecast": "Open forecast", "fc.loading_why": "Loading drivers…", "fc.tab.cash": "Cash-out", "fc.tab.efloat": "Cash-in",

  "hist.title": "History", "hist.range": "Last {n} days", "hist.balances": "Closing balances", "hist.cash": "Cash", "hist.efloat": "E-float",
  "hist.topup": "Top-up arrived", "hist.stockout": "Stock-out", "hist.stockout_days": "Stock-out days", "hist.topups": "Top-ups received",
  "hist.table": "Daily log", "hist.col.cash": "Cash", "hist.col.efloat": "E-float", "hist.col.topup": "Top-ups", "hist.col.flags": "Flags",
  "hist.col.report": "Cash report", "hist.cash_topup": "Cash top-up", "hist.efloat_topup": "E-float top-up", "hist.so.cash": "Cash ran out", "hist.so.efloat": "E-float ran out",
  "hist.none": "No flags",

  "alerts.title": "Alerts", "alerts.open": "Open", "alerts.acked": "Acknowledged", "alerts.ack": "Acknowledge", "alerts.none": "No alerts",
  "alerts.type.risk_high": "High run-out risk", "alerts.type.risk_watch": "Watch: risk rising", "alerts.type.report_missing": "Cash report missing",
  "alerts.type.report_requested": "Cash report requested", "alerts.type.report_gap": "Report needs verification", "alerts.type.capital": "Extra capital suggested",
  "alerts.msg.risk_high": "{agent}: high run-out risk before the next possible top-up (cash {c}%, e-float {e}%, {w}-day window).",
  "alerts.msg.risk_watch": "{agent}: watch, run-out risk is rising (cash {c}%, e-float {e}%, {w}-day window).",
  "alerts.msg.report_missing": "{agent}: no cash report for {date}. Estimated from the ledger, not confirmed today.",
  "alerts.msg.report_requested": "{agent}: daily cash report requested for {date}.",
  "alerts.msg.report_gap": "{agent}: reported cash differs from the ledger-implied cash{gap}. Marked for verification; ledger value used.",
  "alerts.msg.capital": "{agent}: total float may be too small for the coming window; extra capital of about BDT {amount} suggested.",
  "alerts.sev.high": "High", "alerts.sev.watch": "Watch", "alerts.sev.info": "Info",

  "adm.overview.title": "Network overview", "adm.overview.sub": "All 16 agents ranked by run-out risk",
  "kpi.high": "Agents at HIGH", "kpi.watch": "Agents at WATCH", "kpi.unserved": "Expected unserved demand", "kpi.unserved.note": "model estimate, coverage window",
  "kpi.topup": "Planned top-up total", "kpi.topup.note": "cash {c} + e-float {e}", "kpi.capital": "Agents needing capital", "kpi.capital.note": "total float too small",
  "kpi.reports": "Reports to follow up", "kpi.reports.note": "{m} missing or pending · {f} flagged",
  "tbl.rank": "#", "tbl.agent": "Agent", "tbl.cash_risk": "Cash risk", "tbl.ef_risk": "E-float risk", "tbl.runout": "Likely run-out", "tbl.topup": "Recommended top-up",
  "tbl.report": "Report", "tbl.status": "Status", "tbl.capital": "Capital", "tbl.window": "Window",
  "tbl.filter.division": "Division", "tbl.filter.type": "Location type", "tbl.filter.status": "Status", "tbl.filter.reset": "Clear filters",
  "tbl.none": "No agents match these filters", "tbl.cash_short": "cash", "tbl.ef_short": "e-float", "tbl.needs_capital": "Needs capital",
  "tbl.no_runout": "none in 7 days", "tbl.event": "Manual adjustment active",
  "div.title": "Divisions", "div.agents": "{n} agents", "div.worst": "Worst status", "div.topup": "Top-ups BDT {amount}",
  "adm.agent.title": "Agent detail", "adm.agent.back": "Back to overview", "adm.agent.recon": "Reconciliation history", "adm.agent.alerts": "Alert log",
  "adm.agent.reveal": "Demo reveal: what actually happened", "adm.agent.reveal.sub": "Overlays the synthetic ground truth on the charts for the next 7 days.",
  "adm.agent.reveal.unavailable": "Needs 7 full days of data after the date (last origin {date}).",
  "reveal.banner": "DEMO REVEAL: synthetic ground truth, not available to agents or in real life.",
  "reveal.true": "True demand", "reveal.served": "Served (ledger)", "reveal.outcome": "What actually happened", "reveal.unserved": "Unserved BDT {amount}",
  "reveal.stockouts": "Stock-out days: cash {c}, e-float {e}", "reveal.counterfactual": "Balance if no top-up arrived",
  "reveal.breach.yes": "Without a top-up the balance would have fallen below the buffer", "reveal.breach.no": "Without a top-up the balance would have stayed above the buffer",
  "reveal.col.true": "True", "reveal.col.served": "Served",

  "disp.title": "Dispatch plan", "disp.sub": "Recommended top-ups for the next working day: {date}", "disp.cash_total": "Cash to allocate",
  "disp.ef_total": "E-float to allocate", "disp.orders": "Orders raised", "disp.emergency": "Emergency", "disp.planned_n": "Planned",
  "disp.by": "Do by", "disp.ack": "Acknowledge", "disp.schedule": "Schedule", "disp.done": "Mark done", "disp.cancel": "Cancel order",
  "disp.status.proposed": "Proposed", "disp.status.acknowledged": "Acknowledged", "disp.status.scheduled": "Scheduled", "disp.status.done": "Done", "disp.status.cancelled": "Cancelled",
  "disp.no_items": "No top-ups recommended for this date", "disp.needs_capital": "Needs capital: {agents}", "disp.urgent": "Next working day",
  "disp.later": "Can wait", "disp.sched_for": "Scheduled for", "disp.pick_date": "Pick a date", "disp.created": "Order created", "disp.updated": "Order updated",
  "disp.note": "Recommendations only. A person decides and arranges every order.", "disp.risk": "Risk", "disp.runout": "Likely run-out",
  "disp.capital_gap": "Extra capital about BDT {amount}", "disp.orders_log": "Orders",

  "rules.title": "Rules & events", "rules.sub": "Business rules sit outside the model. Changing them re-runs forecasts on a copy of the model's risk settings. Nothing is retrained.",
  "rules.buffer": "Buffer (share of capacity treated as 'effectively out')", "rules.coverage": "Coverage probability for recommended level",
  "rules.min_order": "Minimum top-up (share of capacity)", "rules.high": "HIGH threshold (risk %)", "rules.watch": "WATCH threshold (risk %)",
  "rules.tol": "Reconciliation tolerance (share of ledger cash)", "rules.manual": "Agents whose report stays pending (demo)", "rules.manual.help": "Comma separated agent ids, for example A01",
  "rules.save": "Save rules and re-run forecasts", "rules.saved": "Rules saved. Forecasts re-run.", "rules.reset": "Restore defaults", "rules.hash": "Config fingerprint",
  "rules.bounds": "Allowed: {lo} to {hi}", "rules.invalid": "Check the highlighted values",
  "events.title": "Local event override", "events.sub": "Enter an area event as a demand multiplier. It is applied to the forecast quantiles before the risk simulation.",
  "events.badge": "Manual adjustment, not learned by the model", "events.scope": "Applies to", "events.scope.all": "All agents", "events.scope.division": "A division",
  "events.scope.agent": "One agent", "events.target": "Target", "events.kind": "Event", "events.kind.fair": "Fair", "events.kind.road_closure": "Road closure",
  "events.kind.flood": "Flood", "events.kind.other": "Other", "events.flow": "Affects", "events.flow.both": "Cash-out and cash-in", "events.flow.cashout": "Cash-out only",
  "events.flow.cashin": "Cash-in only", "events.mult": "Demand multiplier", "events.mult.help": "1.0 = no change; 1.5 = 50% more; 0.5 = half", "events.start": "From", "events.end": "To",
  "events.add": "Add event", "events.added": "Event added. Forecasts updated.", "events.none": "No events yet", "events.remove": "Deactivate", "events.removed": "Event deactivated",
  "events.active": "Active", "events.inactive": "Inactive", "events.note": "Note",
  "audit.title": "Audit log", "audit.none": "No entries", "audit.when": "When", "audit.who": "Who", "audit.what": "Action",

  "impact.title": "Impact & model card", "impact.sub": "Offline evaluation, not measured on real upay data", "impact.label": "Simulation on synthetic data",
  "impact.policy.title": "Policy replay: 1 Sep to 24 Dec 2025, 16 agents (115 days)", "impact.policy.stockouts": "Stock-out days", "impact.policy.unserved": "Unserved demand (BDT)",
  "impact.policy.orders": "Orders placed (the cost side)", "impact.policy.cash": "cash {n}", "impact.policy.ef": "e-float {n}",
  "impact.policy.habit": "Agent habit", "impact.policy.hybrid": "Hybrid (recommended)", "impact.policy.model_only": "Model only (just-in-time)",
  "impact.policy.habit.rule": "Order below 30% of capacity, top up to 65%", "impact.policy.hybrid.rule": "Habit buffer raised by the model's requirement at 95% coverage",
  "impact.policy.model_only.rule": "Order only when below the model's recommended level",
  "impact.headline": "Hybrid vs habit: {s}% stock-out days, {u}% unserved demand, but {o}% more orders.",
  "impact.cost": "It is not free: the hybrid places more orders (trips). Whether that is worth it depends on the cost of a trip versus an unserved customer.",
  "impact.model_only": "Model-only (just-in-time) is worse than the agent habit on stock-out days ({d} vs {h}). The model's value is knowing when the habit buffer is not enough, not replacing it.",
  "impact.frontier.title": "Coverage trade-off", "impact.frontier.x": "Orders placed (cost)", "impact.frontier.y": "Stock-out days (harm)",
  "impact.frontier.habit": "Agent habit", "impact.frontier.note": "Coverage is a business dial: more safety means fewer stock-outs but more orders.",
  "impact.type.title": "Stock-out reduction by agent type", "impact.type.garment_note": "Garment needs capital: its 95% requirement exceeds its total float on {p}% of days (average shortfall BDT {s}).",
  "impact.type.rural": "Rural", "impact.type.university": "University", "impact.type.market": "Market", "impact.type.garment": "Garment", "impact.type.remittance_urban": "Remittance urban",
  "impact.acc.title": "Forecast accuracy (WAPE, test Sep to Dec)", "impact.acc.model": "Model", "impact.acc.baseline": "Same weekday last week", "impact.acc.floor": "Synthetic noise floor",
  "impact.acc.cashout": "Cash-out", "impact.acc.cashin": "Cash-in", "impact.acc.cover": "80% interval actually covers {a}% (cash-out) and {b}% (cash-in)",
  "impact.acc.unseen_agent": "Unseen agent: {u} vs {s} when seen (cash-out)", "impact.acc.unseen_festival": "Unseen festival (Eid-ul-Adha held out): cash-out {a}, cash-in {b}",
  "impact.lim.title": "Limitations", "impact.lim.0": "Synthetic data: the model recovers patterns that were planted, so results validate the pipeline, not real-world accuracy.",
  "impact.lim.1": "One year of data (2025) only.", "impact.lim.2": "The model was trained on all of 2025, so replay dates are in-sample for the deployed model.",
  "impact.lim.3": "The risk engine assumes independent days, so tail risk is probably understated.", "impact.lim.4": "Recommendations only: humans decide, nothing is autonomous.",
  "impact.lim.5": "Needs governed upay data for validation before any pilot.",
  "impact.card.title": "Model card", "impact.card.model": "Model", "impact.card.trained": "Trained on", "impact.card.libs": "Libraries", "impact.card.horizon": "Horizon",
  "impact.card.horizon_v": "7 days, quantiles P10, P25, P50, P75, P90", "impact.card.rules": "Business rules (buffers, coverage, top-up sizing, overrides) live outside the model.",
  "impact.card.llm": "No LLM is used for numbers or decisions. Explanations are deterministic templates.",
  "feat.base": "Average level",
} as const;

export default en;
export type DictKey = keyof typeof en;
